linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref  
    - gosimple
    - govet
    - gocheckcompilerdirectives
    - gosec
    - ineffassign
    - staticcheck
    - typecheck
    - contextcheck
    - durationcheck     
    - loggercheck
    - nilerr
    - prealloc
    - predeclared
    - reassign
    - unconvert

linters-settings:
  staticcheck:
    checks:
    - all
    - '-SA1024'