version: '3.8'
services:
  postgresql:
    container_name: hezzl_postgres
    image: postgres:12.2-alpine    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend-network
    volumes:
      - ./pg_data:/var/lib/postgresql

  redis:
    container_name: hezzl_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nats:
    container_name: hezzl_nats
    image: nats:latest
    command: "--js --m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - backend-network

  clickhouse:
    container_name: hezzl_clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "19000:9000"
    networks:
      - backend-network

  hezzl-backend:
    build: .
    container_name: "hezzl-rest-api"
    image: hezzl:latest
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
      - HTTP_ADDR="8080"
      - METRICS_PORT="3030"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_HOST="hezzl_postgres"
      - POSTGRES_PORT=5432
      - POSTGRES_DB="postgres"
      - POSTGRES_SSLMODE="disable"
      - POSTGRES_MAX_OPEN_CONNS=20
      - POSTGRES_MAX_IDLE_CONNS=10
      - REDIS_HOST=hezzl_redis
      - REDIS_PORT="6379"
    depends_on:
      - postgresql

networks:
  backend-network:
    driver: bridge