version: '3.8'
services:
  postgresql:
    container_name: hezzl_postgres
    image: postgres:12.2-alpine    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - backend-network
    volumes:
      - ./pg_data:/var/lib/postgresql

  redis:
    container_name: hezzl_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nats:
    container_name: hezzl_nats
    image: nats-streaming:latest
    entrypoint:
      - /nats-streaming-server
      - -cid
      - main_cluster
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:6222:6222"
      - "127.0.0.1:8222:8222"
    restart: always
    tty: true
    networks:
      - backend-network

  clickhouse:
    container_name: hezzl_clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "19000:9000"
    networks:
      - backend-network
      
  hezzl-backend:
    build: .
    container_name: "hezzl-rest-api"
    image: hezzl:latest
    ports:
      - "8080:8080"
    networks:
      - backend-network    
    depends_on:
      - postgresql

networks:
  backend-network:
    driver: bridge